"use server";

import { revalidatePath } from "next/cache";

import { createClient } from "@/lib/supabase/server";
import type { TablesUpdate } from "@/lib/database.types";

async function assertAhcUser() {
  const supabase = createClient();
  const {
    data: { user },
    error: userError,
  } = await supabase.auth.getUser();
  if (userError || !user) return { ok: false as const, error: "Not signed in" };
  const { data: profile } = await supabase
    .from("profiles")
    .select("role")
    .eq("id", user.id)
    .maybeSingle();
  if (!profile || !["phil", "zarina", "ahc_super"].includes(profile.role)) {
    return { ok: false as const, error: "Restricted to AHC team members" };
  }
  return { ok: true as const, supabase };
}

export type ScheduleTaskResult =
  | { ok: true }
  | { ok: false; error: string; fieldErrors?: Record<string, string> };

function getStr(value: FormDataEntryValue | null): string | null {
  if (typeof value !== "string" || !value.trim()) return null;
  return value.trim();
}

function getDate(value: FormDataEntryValue | null): string | null {
  if (typeof value !== "string" || !value.trim()) return null;
  return value;
}

function getInt(value: FormDataEntryValue | null): number | null {
  if (typeof value !== "string" || !value.trim()) return null;
  const num = parseInt(value, 10);
  return Number.isFinite(num) ? num : null;
}

export async function updateScheduleTask(
  taskId: string,
  projectId: string,
  formData: FormData,
): Promise<ScheduleTaskResult> {
  const auth = await assertAhcUser();
  if (!auth.ok) return auth;

  const update: TablesUpdate<"schedule_tasks"> = {
    task_name: getStr(formData.get("task_name")) ?? undefined,
    description: getStr(formData.get("description")),
    phase: getStr(formData.get("phase")),
    assigned_to: getStr(formData.get("assigned_to")),
    status: getStr(formData.get("status")),
    duration_days: getInt(formData.get("duration_days")),
    start_date: getDate(formData.get("start_date")),
    end_date: getDate(formData.get("end_date")),
    predecessors: getStr(formData.get("predecessors")),
    is_at_risk: formData.get("is_at_risk") === "on",
    is_internal: formData.get("is_internal") === "on",
    non_ahc_delay: formData.get("non_ahc_delay") === "on",
  };

  const { error } = await auth.supabase
    .from("schedule_tasks")
    .update(update)
    .eq("id", taskId);
  if (error) return { ok: false, error: error.message };

  revalidatePath(`/projects/${projectId}`);
  revalidatePath(`/projects/${projectId}/schedule`);
  return { ok: true };
}

// Capture the current dates as the committed baseline. Everything downstream
// measures against this, so it is deliberately explicit rather than automatic -
// a baseline that moves on its own is not a baseline.
//
// `onlyUnbaselined` covers the common case of tasks added after the fact: it
// baselines the new rows without disturbing the committed dates on the rest,
// which is what you want when scope is added mid-job.
export async function setScheduleBaseline(
  projectId: string,
  opts: { label?: string | null; onlyUnbaselined?: boolean } = {},
): Promise<{ ok: true; count: number } | { ok: false; error: string }> {
  const auth = await assertAhcUser();
  if (!auth.ok) return auth;

  // database.types.ts is generated by the Supabase CLI, which is not installed
  // here, so it does not yet know about the baseline columns added in migration
  // 0032. The casts below are that gap and nothing more - drop them the next
  // time `npm run db:types` is run.
  let query = auth.supabase
    .from("schedule_tasks")
    .select("id, start_date, end_date, duration_days")
    .eq("project_id", projectId);
  if (opts.onlyUnbaselined) {
    query = (query as unknown as { is: (c: string, v: null) => typeof query }).is(
      "baseline_end",
      null,
    );
  }

  const { data: tasks, error: readError } = await query;
  if (readError) return { ok: false, error: readError.message };
  if (!tasks?.length) return { ok: true, count: 0 };

  const stamp = new Date().toISOString();
  const label = opts.label?.trim() || `Baseline ${stamp.slice(0, 10)}`;

  let count = 0;
  for (const t of tasks) {
    // A task with no dates has nothing to commit to.
    if (!t.start_date && !t.end_date) continue;
    const { error } = await auth.supabase
      .from("schedule_tasks")
      .update({
        baseline_start: t.start_date,
        baseline_end: t.end_date,
        baseline_duration_days: t.duration_days,
        baseline_set_at: stamp,
        baseline_label: label,
      } as never)
      .eq("id", t.id);
    if (error) return { ok: false, error: error.message };
    count++;
  }

  revalidatePath(`/projects/${projectId}`);
  revalidatePath(`/projects/${projectId}/schedule`);
  return { ok: true, count };
}

// Push the CPM projection into the working dates. This is the "reflow" step:
// the projection is always live and read-only, and this is the explicit act of
// accepting it as the new plan. The baseline is untouched, so the slip stays
// visible after the reflow.
export async function applyProjectedDates(
  projectId: string,
  updates: { wbs: string; start: string; end: string }[],
): Promise<{ ok: true; count: number } | { ok: false; error: string }> {
  const auth = await assertAhcUser();
  if (!auth.ok) return auth;
  if (!updates.length) return { ok: true, count: 0 };

  let count = 0;
  for (const u of updates) {
    const { error } = await auth.supabase
      .from("schedule_tasks")
      .update({ start_date: u.start, end_date: u.end })
      .eq("project_id", projectId)
      .eq("wbs_code", u.wbs);
    if (error) return { ok: false, error: error.message };
    count++;
  }

  revalidatePath(`/projects/${projectId}`);
  revalidatePath(`/projects/${projectId}/schedule`);
  return { ok: true, count };
}

export async function deleteScheduleTask(
  taskId: string,
  projectId: string,
): Promise<{ ok: true } | { ok: false; error: string }> {
  const auth = await assertAhcUser();
  if (!auth.ok) return auth;

  const { error } = await auth.supabase
    .from("schedule_tasks")
    .delete()
    .eq("id", taskId);
  if (error) return { ok: false, error: error.message };

  revalidatePath(`/projects/${projectId}`);
  revalidatePath(`/projects/${projectId}/schedule`);
  return { ok: true };
}
