// Mac Mini relay: receives chat requests from the deployed PM Platform
// (Vercel) and answers them using the Claude Agent SDK with subscription OAuth.
//
// Auth: Bearer token in Authorization header (RELAY_SHARED_SECRET).
// Tools: list_documents, read_document, search_documents - run in-process,
// query Supabase directly with the service-role key.
//
// Env vars (read from .env or process):
//   PORT                       - HTTP port (default 8787)
//   RELAY_SHARED_SECRET        - the token Vercel must send to auth requests
//   SUPABASE_URL               - same as the Vercel app's NEXT_PUBLIC_SUPABASE_URL
//   SUPABASE_SERVICE_ROLE_KEY  - service-role key (bypasses RLS)
//   CLAUDE_CODE_OAUTH_TOKEN    - generated by `claude setup-token` on this Mac
//   CLAUDE_MODEL               - optional, defaults to claude-sonnet-4-5
//
// Usage:
//   npm start

import { readFileSync, existsSync } from "node:fs";
import Fastify from "fastify";
import { createClient } from "@supabase/supabase-js";
import { query, createSdkMcpServer } from "@anthropic-ai/claude-agent-sdk";
import { buildTools } from "./tools.mjs";

// ============ ENV ============

function loadEnvFile() {
  if (!existsSync(".env")) return {};
  const out = {};
  for (const line of readFileSync(".env", "utf8").split("\n")) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eq = trimmed.indexOf("=");
    if (eq === -1) continue;
    out[trimmed.slice(0, eq)] = trimmed.slice(eq + 1);
  }
  return out;
}

const fileEnv = loadEnvFile();
const env = (key) => process.env[key] ?? fileEnv[key];

const PORT = parseInt(env("PORT") || "8787", 10);
const SHARED_SECRET = env("RELAY_SHARED_SECRET");
const SUPABASE_URL = env("SUPABASE_URL");
const SUPABASE_SERVICE_KEY = env("SUPABASE_SERVICE_ROLE_KEY");
const CLAUDE_TOKEN = env("CLAUDE_CODE_OAUTH_TOKEN");
const MODEL = env("CLAUDE_MODEL") || "claude-sonnet-4-5";

const missing = [];
if (!SHARED_SECRET) missing.push("RELAY_SHARED_SECRET");
if (!SUPABASE_URL) missing.push("SUPABASE_URL");
if (!SUPABASE_SERVICE_KEY) missing.push("SUPABASE_SERVICE_ROLE_KEY");
if (!CLAUDE_TOKEN) missing.push("CLAUDE_CODE_OAUTH_TOKEN");
if (missing.length) {
  console.error(`Missing required env vars: ${missing.join(", ")}`);
  console.error("Put them in relay/.env or export them in the shell.");
  process.exit(1);
}

// Make the OAuth token visible to the SDK (which reads it from process.env).
process.env.CLAUDE_CODE_OAUTH_TOKEN = CLAUDE_TOKEN;

// ============ SUPABASE + TOOLS ============

const supabase = createClient(SUPABASE_URL, SUPABASE_SERVICE_KEY, {
  auth: { persistSession: false },
});

const mcpServer = createSdkMcpServer({
  name: "pm-platform-docs",
  version: "0.1.0",
  tools: buildTools(supabase),
});

// ============ FASTIFY ============

const fastify = Fastify({
  logger: { level: "info" },
  bodyLimit: 1024 * 1024, // 1 MB max request body
});

fastify.addHook("onRequest", async (request, reply) => {
  if (request.url === "/health") return;
  const header = request.headers.authorization || "";
  if (!header.startsWith("Bearer ")) {
    reply.code(401).send({ error: "Missing bearer token" });
    return reply;
  }
  if (header.slice(7) !== SHARED_SECRET) {
    reply.code(403).send({ error: "Invalid bearer token" });
    return reply;
  }
});

fastify.get("/health", async () => ({ ok: true, ts: new Date().toISOString() }));

// POST /chat
//   body: { project_id, project_name, question, history? }
//     history: [{ role: 'user' | 'assistant', content: string }] - optional, last N turns
//   returns: { answer: string, tool_calls: [...], usage?: {...} }
fastify.post("/chat", async (request, reply) => {
  const { project_id, project_name, question, history } = request.body || {};
  if (!project_id || typeof project_id !== "string") {
    reply.code(400).send({ error: "project_id required" });
    return;
  }
  if (!question || typeof question !== "string") {
    reply.code(400).send({ error: "question required" });
    return;
  }

  const systemPrompt = [
    "You are an AI assistant for the AHC Solar PM Platform answering questions about a specific solar EPC project's documents.",
    "",
    `The user is asking about project: ${project_name || project_id} (UUID: ${project_id}).`,
    "",
    "How to answer:",
    "1. Use the `list_documents` tool first if you don't know what's in the project. Pass the project UUID above.",
    "2. Use `search_documents` to find specific keywords across all docs at once.",
    "3. Use `read_document` to read the full text of specific documents that look relevant.",
    "4. Answer based ONLY on the document contents. Quote exact contract language when discussing legal/financial terms.",
    "5. Cite which document(s) and section number(s) your answer comes from.",
    "6. If the documents don't contain the answer, say so clearly. Do not invent values.",
    "7. Be concise. Use markdown tables for multi-attribute answers. No em dashes - use regular dashes or rewrite.",
  ].join("\n");

  // Build the user prompt. If history is provided, prepend it as context.
  let promptText = "";
  if (Array.isArray(history) && history.length > 0) {
    promptText += "Prior conversation (for context):\n";
    for (const turn of history.slice(-6)) {
      const who = turn.role === "user" ? "User" : "Assistant";
      promptText += `\n${who}: ${turn.content}\n`;
    }
    promptText += "\n---\n\nCurrent question:\n";
  }
  promptText += question;

  const startedAt = Date.now();
  const toolCalls = [];
  let answerText = "";
  let usage = null;
  let stopReason = null;

  try {
    const q = query({
      prompt: promptText,
      options: {
        model: MODEL,
        systemPrompt,
        mcpServers: { docs: mcpServer },
        allowedTools: [
          "mcp__docs__list_documents",
          "mcp__docs__read_document",
          "mcp__docs__search_documents",
        ],
        permissionMode: "bypassPermissions",
        maxTurns: 12,
      },
    });

    for await (const message of q) {
      if (message.type === "assistant") {
        // Accumulate text content blocks
        const content = message.message?.content;
        if (Array.isArray(content)) {
          for (const block of content) {
            if (block.type === "text" && typeof block.text === "string") {
              // Latest assistant text replaces; we want the final one
              answerText = block.text;
            } else if (block.type === "tool_use") {
              toolCalls.push({
                name: block.name,
                input: block.input,
              });
            }
          }
        }
      } else if (message.type === "result") {
        usage = message.usage ?? null;
        stopReason = message.stop_reason ?? null;
      }
    }
  } catch (err) {
    request.log.error({ err }, "query() failed");
    reply.code(500).send({ error: err.message || "Internal error" });
    return;
  }

  const elapsedMs = Date.now() - startedAt;
  request.log.info(
    { project_id, elapsedMs, tool_calls: toolCalls.length, answer_chars: answerText.length },
    "chat answered",
  );

  return {
    answer: answerText,
    tool_calls: toolCalls,
    stop_reason: stopReason,
    usage,
    elapsed_ms: elapsedMs,
  };
});

// POST /extract-project-details
//   body: { project_id }
//   Looks up the project's prime contract, asks Claude to extract structured
//   project metadata as JSON, returns it for confirmation in the UI before
//   the user applies it to the projects row.
fastify.post("/extract-project-details", async (request, reply) => {
  const { project_id } = request.body || {};
  if (!project_id || typeof project_id !== "string") {
    reply.code(400).send({ error: "project_id required" });
    return;
  }

  const { data: docs, error: docError } = await supabase
    .from("project_documents")
    .select("file_name, extracted_text")
    .eq("project_id", project_id)
    .eq("category", "prime_contract")
    .eq("text_status", "ready");

  if (docError) {
    reply.code(500).send({ error: docError.message });
    return;
  }
  if (!docs || docs.length === 0) {
    reply.code(404).send({
      error:
        "No prime contract found for this project. Upload one and tag its category as 'prime_contract' first.",
    });
    return;
  }

  // Concatenate all prime contracts (usually 1). Cap at 600k chars (~150k
  // tokens) to stay safely within the Sonnet context window. Most prime
  // EPCs sit under 200k tokens, but trim defensively.
  const MAX_CHARS = 600_000;
  let contractText = docs
    .map((d) => `=== ${d.file_name} ===\n\n${d.extracted_text}`)
    .join("\n\n");
  if (contractText.length > MAX_CHARS) {
    contractText =
      contractText.slice(0, MAX_CHARS) +
      "\n\n[... truncated for context window]";
  }

  const systemPrompt = [
    "You extract structured project metadata from a prime EPC (Engineering, Procurement, Construction) contract for a solar project.",
    "",
    "Read the contract carefully. Return ONLY a single JSON object (no markdown fences, no commentary before or after). Use exactly these field names:",
    "",
    "{",
    '  "client": string | null,            // The Owner / customer entity (e.g. "Dimension Energy", "Sweet Spring Solar, LLC")',
    '  "contract_value": number | null,    // Contract price in USD as a plain number (no commas, no $ sign)',
    '  "ntp_date": string | null,          // Notice to Proceed date as YYYY-MM-DD',
    '  "cod_date": string | null,          // Commercial Operation Date target as YYYY-MM-DD (use Guaranteed Placed in Service Completion Date if COD is not directly given)',
    '  "zip_code": string | null,          // Site zip code (Exhibit A or Exhibit I typically lists the site)',
    '  "ld_rate_per_mwdc_per_day": number | null,  // Delay Damages rate, dollars per MWDC per day',
    '  "retainage_pct": number | null,     // Retainage percentage withheld from each progress payment',
    '  "ld_cap_pct": number | null,        // Liquidated Damages aggregate cap as a percentage of contract price',
    '  "notes": string                     // Brief notes about any uncertain fields, conflicts, or where you sourced unusual values',
    "}",
    "",
    "Use null when you genuinely cannot find a value. Do not guess. Do not invent dates.",
    "Return ONLY the JSON object. No prose. No code fences.",
  ].join("\n");

  const userPrompt = [
    "Contract text follows. Extract the project metadata.",
    "",
    contractText,
  ].join("\n");

  const startedAt = Date.now();
  let raw = "";

  try {
    const q = query({
      prompt: userPrompt,
      options: {
        model: MODEL,
        systemPrompt,
        // No tools - this is a pure one-shot extraction. The agent does not
        // need to read other documents; the prime contract text is already
        // in the prompt.
        permissionMode: "bypassPermissions",
        maxTurns: 1,
      },
    });

    for await (const message of q) {
      if (message.type === "assistant") {
        const content = message.message?.content;
        if (Array.isArray(content)) {
          for (const block of content) {
            if (block.type === "text" && typeof block.text === "string") {
              raw = block.text;
            }
          }
        }
      }
    }
  } catch (err) {
    request.log.error({ err }, "extraction query failed");
    reply.code(500).send({ error: err.message || "Internal error" });
    return;
  }

  if (!raw) {
    reply.code(500).send({ error: "Claude returned no text" });
    return;
  }

  // Claude sometimes wraps the JSON in prose or code fences despite
  // instructions. Find the outermost { ... } and parse that.
  let parsed;
  const firstBrace = raw.indexOf("{");
  const lastBrace = raw.lastIndexOf("}");
  if (firstBrace === -1 || lastBrace === -1 || lastBrace < firstBrace) {
    reply.code(500).send({
      error: "Claude response did not contain a JSON object",
      raw: raw.slice(0, 2000),
    });
    return;
  }
  const jsonText = raw.slice(firstBrace, lastBrace + 1);
  try {
    parsed = JSON.parse(jsonText);
  } catch (err) {
    request.log.error({ raw: raw.slice(0, 500) }, "JSON parse failed");
    reply.code(500).send({
      error: "Claude returned invalid JSON",
      raw: raw.slice(0, 2000),
    });
    return;
  }

  const elapsedMs = Date.now() - startedAt;
  request.log.info({ project_id, elapsedMs }, "extracted project details");

  return {
    fields: parsed,
    elapsed_ms: elapsedMs,
    source_documents: docs.map((d) => d.file_name),
  };
});

// POST /extract-sov
//   body: { project_id }
//   Reads the project's prime contract documents, asks Claude to extract the
//   Schedule of Values (Exhibit E) as structured rows, returns them for
//   confirmation before insertion into wbs_sov.
fastify.post("/extract-sov", async (request, reply) => {
  const { project_id } = request.body || {};
  if (!project_id || typeof project_id !== "string") {
    reply.code(400).send({ error: "project_id required" });
    return;
  }

  // Look for prime contracts OR exhibit category docs whose file_name hints
  // at being Exhibit E (the SOV). Fall back to all prime contracts if no
  // obvious SOV doc is found.
  const { data: exhibitDocs } = await supabase
    .from("project_documents")
    .select("file_name, extracted_text")
    .eq("project_id", project_id)
    .eq("category", "exhibit")
    .eq("text_status", "ready")
    .ilike("file_name", "%exhibit_e%");

  const { data: primeDocs } = await supabase
    .from("project_documents")
    .select("file_name, extracted_text")
    .eq("project_id", project_id)
    .eq("category", "prime_contract")
    .eq("text_status", "ready");

  // Prefer standalone Exhibit E if found; otherwise scan the prime contract
  // (which usually has Exhibit E attached at the end).
  const sourceDocs =
    exhibitDocs && exhibitDocs.length > 0 ? exhibitDocs : primeDocs;

  if (!sourceDocs || sourceDocs.length === 0) {
    reply.code(404).send({
      error:
        "Could not find a prime contract or Exhibit E for this project. Upload one first.",
    });
    return;
  }

  const MAX_CHARS = 600_000;
  let combined = sourceDocs
    .map((d) => `=== ${d.file_name} ===\n\n${d.extracted_text}`)
    .join("\n\n");
  if (combined.length > MAX_CHARS) {
    combined = combined.slice(0, MAX_CHARS) + "\n\n[... truncated]";
  }

  const systemPrompt = [
    "You extract the Schedule of Values (SOV) from a solar EPC prime contract. The SOV is usually labeled Exhibit E and contains a list of payment milestones / line items with WBS codes, descriptions, percentages, and dollar amounts.",
    "",
    "Return ONLY a JSON object (no markdown fences, no commentary) of this exact shape:",
    "",
    "{",
    '  "items": [',
    "    {",
    '      "wbs_code": string,             // e.g. "1.00", "1.01", "8.03"',
    '      "description": string,          // e.g. "Engineering services (30% IFC)"',
    '      "contract_value": number | null // dollar amount (no $ or commas)',
    "    },",
    "    ...",
    "  ],",
    '  "total_contract_value": number | null,  // sum of items, or the contract value stated in the SOV',
    '  "notes": string                          // brief notes about ambiguity, alternate versions found, etc.',
    "}",
    "",
    "Rules:",
    "- Include every line item, including milestone-only entries that may have 0 value (e.g. Final Completion may show as 200% of punchlist holdback).",
    "- For lines with non-numeric values (e.g. '200% of punchlist holdback'), set contract_value to null and put the description verbatim.",
    "- If the contract contains multiple SOV versions (e.g. an updated Exhibit E in an amendment), use the MOST RECENT one and note this.",
    "- Return ONLY the JSON object. No prose.",
  ].join("\n");

  const userPrompt = [
    "Document text follows. Extract the Schedule of Values.",
    "",
    combined,
  ].join("\n");

  const startedAt = Date.now();
  let raw = "";

  try {
    const q = query({
      prompt: userPrompt,
      options: {
        model: MODEL,
        systemPrompt,
        permissionMode: "bypassPermissions",
        maxTurns: 1,
      },
    });

    for await (const message of q) {
      if (message.type === "assistant") {
        const content = message.message?.content;
        if (Array.isArray(content)) {
          for (const block of content) {
            if (block.type === "text" && typeof block.text === "string") {
              raw = block.text;
            }
          }
        }
      }
    }
  } catch (err) {
    request.log.error({ err }, "SOV extraction query failed");
    reply.code(500).send({ error: err.message || "Internal error" });
    return;
  }

  if (!raw) {
    reply.code(500).send({ error: "Claude returned no text" });
    return;
  }

  // Tolerant JSON extraction: take everything between the outermost { ... }.
  const firstBrace = raw.indexOf("{");
  const lastBrace = raw.lastIndexOf("}");
  if (firstBrace === -1 || lastBrace === -1 || lastBrace < firstBrace) {
    reply.code(500).send({
      error: "Claude response did not contain a JSON object",
      raw: raw.slice(0, 2000),
    });
    return;
  }

  let parsed;
  try {
    parsed = JSON.parse(raw.slice(firstBrace, lastBrace + 1));
  } catch (err) {
    request.log.error({ raw: raw.slice(0, 500) }, "SOV JSON parse failed");
    reply.code(500).send({
      error: "Claude returned invalid JSON",
      raw: raw.slice(0, 2000),
    });
    return;
  }

  if (!Array.isArray(parsed?.items)) {
    reply.code(500).send({
      error: "Extracted JSON has no 'items' array",
      raw: raw.slice(0, 2000),
    });
    return;
  }

  const elapsedMs = Date.now() - startedAt;
  request.log.info(
    { project_id, elapsedMs, item_count: parsed.items.length },
    "extracted SOV",
  );

  return {
    items: parsed.items,
    total_contract_value: parsed.total_contract_value ?? null,
    notes: parsed.notes ?? "",
    source_documents: sourceDocs.map((d) => d.file_name),
    elapsed_ms: elapsedMs,
  };
});

// POST /extract-po-payment-terms
//   body: { procurement_order_id }
//   Reads the document linked to this PO (procurement_orders.document_id),
//   asks Claude to extract the payment milestone schedule, returns it for
//   confirmation before insertion into procurement_payments.
fastify.post("/extract-po-payment-terms", async (request, reply) => {
  const { procurement_order_id } = request.body || {};
  if (!procurement_order_id || typeof procurement_order_id !== "string") {
    reply.code(400).send({ error: "procurement_order_id required" });
    return;
  }

  // Get the PO and its linked document.
  const { data: po, error: poErr } = await supabase
    .from("procurement_orders")
    .select(
      "po_number, vendor_name, total_value, ordered_date, expected_delivery_date, actual_delivery_date, signed_at, linked_delivery_task_wbs_code, document_id, project_id",
    )
    .eq("id", procurement_order_id)
    .maybeSingle();
  if (poErr || !po) {
    reply.code(404).send({ error: poErr?.message ?? "PO not found" });
    return;
  }
  if (!po.document_id) {
    reply.code(404).send({
      error: "This PO has no linked document. Upload the PO PDF and link it first.",
    });
    return;
  }

  const { data: doc, error: docErr } = await supabase
    .from("project_documents")
    .select("file_name, extracted_text, text_status")
    .eq("id", po.document_id)
    .maybeSingle();
  if (docErr || !doc) {
    reply.code(404).send({ error: "Linked document not found" });
    return;
  }
  if (doc.text_status !== "ready" || !doc.extracted_text) {
    reply.code(400).send({
      error: `Linked document text is not ready (status=${doc.text_status}). Try again after text extraction completes.`,
    });
    return;
  }

  const MAX_CHARS = 300_000;
  let docText = doc.extracted_text;
  if (docText.length > MAX_CHARS) {
    docText = docText.slice(0, MAX_CHARS) + "\n\n[... truncated]";
  }

  const systemPrompt = [
    "You extract the payment milestone schedule from a Purchase Order (PO) document.",
    "",
    "The PO is for solar equipment or services (modules, inverters, racking, transformers, etc.) and typically contains a payment terms section like '20% deposit on PO release, 70% on delivery, 10% on commissioning' or specific milestone dates.",
    "",
    "Return ONLY a JSON object (no markdown fences, no commentary) of this exact shape:",
    "",
    "{",
    '  "milestones": [',
    "    {",
    '      "milestone_name": string,      // e.g. "Deposit", "Delivery", "Commissioning", "Net 30 from invoice"',
    '      "pct_of_total": number | null, // percentage of PO total (0-100). null if amount is fixed, not a percentage',
    '      "amount": number | null,       // dollar amount; if only a pct is given compute it from PO total',
    '      "trigger_event": string,       // what triggers the payment: "PO release", "Delivery", "Commissioning", "Net 30 from invoice", "Substantial completion", etc.',
    '      "expected_date": string | null,// YYYY-MM-DD if a specific date is given OR computable (e.g. "Net 30 after delivery" + expected delivery date)',
    '      "notes": string                // any caveats, conditions, or source phrasing',
    "    }",
    "  ],",
    '  "total_pct": number | null,         // sum of pct_of_total across milestones (should be 100 if all percentages)',
    '  "payment_terms_summary": string,    // human-readable summary, e.g. "20% deposit / 70% delivery / 10% commissioning"',
    '  "notes": string                     // notes about ambiguous terms, multiple schedules, or assumptions',
    "}",
    "",
    "Context about this PO:",
    `  Vendor: ${po.vendor_name}`,
    `  PO Number: ${po.po_number ?? "(unknown)"}`,
    `  Total Value: $${po.total_value ?? "(unknown)"}`,
    `  Ordered Date: ${po.ordered_date ?? "(unknown)"}`,
    `  Signed Date: ${po.signed_at ? po.signed_at.slice(0, 10) : "(unknown)"}`,
    `  Expected Delivery: ${po.expected_delivery_date ?? "(unknown)"}`,
    `  Actual Delivery: ${po.actual_delivery_date ?? "(unknown)"}`,
    `  Linked schedule delivery task: ${po.linked_delivery_task_wbs_code ?? "(none - PO not linked to schedule)"}`,
    "",
    `IMPORTANT: When 'Expected Delivery' is set above, USE IT as the anchor for any Net X after delivery calculations - it comes from the project schedule and is more authoritative than any shipping estimate in the PDF text. Use the PDF shipping boilerplate (e.g. '5-7 day shipping') ONLY when Expected Delivery is unknown.`,
    "",
    "Rules:",
    "- If the PO uses percentages, fill pct_of_total AND compute amount from the PO total value.",
    "- If the PO uses fixed dollar amounts, fill amount and leave pct_of_total null.",
    "- IMPORTANT - Net X interpretation rule for solar EPC equipment POs: When the PO is for EQUIPMENT (transformers, modules, inverters, racking, reclosers, switchgear, monitoring gear, etc.) and the payment term reads 'Net 30' / 'Net 45' / 'Net X' WITHOUT explicitly stating what it runs from, ALWAYS interpret it as 'Net X after DELIVERY' - never as 'Net X from invoice'. AHC's standard is: equipment doesn't get paid until it arrives on site. So set trigger_event = 'Net X after delivery', and include a note that the PO was ambiguous and you applied the equipment default.",
    "- Use 'Net X from invoice' or 'Net X from PO release' only when the PO EXPLICITLY says so.",
    "",
    "- COMPUTE expected_date AGGRESSIVELY. Don't return null when you have enough signals to estimate. Use this priority order:",
    "  1. If the PO explicitly states a specific date for a milestone, use it.",
    "  2. If 'Expected Delivery' is set in the PO context above, anchor against it.",
    "  3. If the PO text contains a DocuSign signature date, signed-on date, or executed date, use that as the deposit / PO-release expected_date.",
    "  4. If lead time + shipping days are stated (e.g. 'In stock, ready to ship' + '5-7 day shipping'), compute delivery = sign_date + shipping_days. Use the upper bound (e.g. 7 days) to stay conservative.",
    "  5. For Net X milestones, expected_date = trigger_event_date + X days (delivery + 30, invoice + 30, etc).",
    "  6. Only return null when there is genuinely no anchor date AND no lead time signal anywhere in the document.",
    "- When you compute a date by estimation rather than reading a stated date, mention the reasoning in the milestone's notes (e.g. 'Estimated: sign_date 5/3 + 7 day shipping + Net 30 = 6/9').",
    "- Return ONLY the JSON. No prose.",
  ].join("\n");

  const userPrompt = [
    "Purchase Order document text follows. Extract the payment milestone schedule.",
    "",
    `=== ${doc.file_name} ===`,
    "",
    docText,
  ].join("\n");

  const startedAt = Date.now();
  let raw = "";

  try {
    const q = query({
      prompt: userPrompt,
      options: {
        model: MODEL,
        systemPrompt,
        permissionMode: "bypassPermissions",
        maxTurns: 1,
      },
    });

    for await (const message of q) {
      if (message.type === "assistant") {
        const content = message.message?.content;
        if (Array.isArray(content)) {
          for (const block of content) {
            if (block.type === "text" && typeof block.text === "string") {
              raw = block.text;
            }
          }
        }
      }
    }
  } catch (err) {
    request.log.error({ err }, "PO extraction query failed");
    reply.code(500).send({ error: err.message || "Internal error" });
    return;
  }

  if (!raw) {
    reply.code(500).send({ error: "Claude returned no text" });
    return;
  }

  const firstBrace = raw.indexOf("{");
  const lastBrace = raw.lastIndexOf("}");
  if (firstBrace === -1 || lastBrace === -1 || lastBrace < firstBrace) {
    reply.code(500).send({
      error: "Claude response did not contain a JSON object",
      raw: raw.slice(0, 2000),
    });
    return;
  }

  let parsed;
  try {
    parsed = JSON.parse(raw.slice(firstBrace, lastBrace + 1));
  } catch (err) {
    request.log.error({ raw: raw.slice(0, 500) }, "PO JSON parse failed");
    reply.code(500).send({
      error: "Claude returned invalid JSON",
      raw: raw.slice(0, 2000),
    });
    return;
  }

  if (!Array.isArray(parsed?.milestones)) {
    reply.code(500).send({
      error: "Extracted JSON has no 'milestones' array",
      raw: raw.slice(0, 2000),
    });
    return;
  }

  const elapsedMs = Date.now() - startedAt;
  request.log.info(
    { procurement_order_id, elapsedMs, milestone_count: parsed.milestones.length },
    "extracted PO payment terms",
  );

  return {
    milestones: parsed.milestones,
    total_pct: parsed.total_pct ?? null,
    payment_terms_summary: parsed.payment_terms_summary ?? "",
    notes: parsed.notes ?? "",
    source_document: doc.file_name,
    elapsed_ms: elapsedMs,
  };
});

// ============ START ============

try {
  await fastify.listen({ port: PORT, host: "127.0.0.1" });
  console.log(`Relay listening on http://127.0.0.1:${PORT}`);
  console.log(`Model: ${MODEL}`);
  console.log(`Supabase: ${SUPABASE_URL}`);
} catch (err) {
  console.error("Failed to start:", err);
  process.exit(1);
}
